name: Install Dependencies
on:
  workflow_call:
  workflow_dispatch:

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash
